spring.datasource.url=jdbc:postgresql://localhost:5433/katadb
spring.datasource.username=user
spring.datasource.password=password

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=false
spring.jpa.properties.hibernate.generate_statistics=true
logging.level.org.hibernate.stat=DEBUG

# Show query parameters
logging.level.org.hibernate.orm.jdbc.bind=TRACE
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
